---
# tasks file for ansible-elastic-filebeat
- include_tasks: "{{ ansible_os_family  }}.yml"
  tags:
    - install-packages

- name: Install Filebeat
  package:
    name: filebeat
    state: present
  notify: restart_filebeat
  tags:
    - install-packages
  become: True

- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_filebeat
  become: True

- name: Establishing modules
  template:
    src: modules/{{ item }}.yml.j2
    dest: "/etc/filebeat/modules.d/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_filebeat
  become: True
  with_items: "{{ filebeat_modules }}"

- name: Disabling modules
  file:
    path: "/etc/filebeat/modules.d/{{ item }}.yml"
    state: absent
  with_items: "{{ filebeat_list_modules }}"
  when: (item not in filebeat_modules) and (item not in filebeat_modules_exclude)
  become: True
  notify: restart_filebeat

- name: List all disabled modules
  find:
    paths: "/etc/filebeat/modules.d"
    patterns: "*.disabled"
  register: filebeat_disabled_modules

- name: Erase unmanaged modules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ filebeat_disabled_modules.files }}"
  become: True
